//to use switch case to play kbc
#include<iostream.h>
#include<conio.h>
void main()
{clrscr();
 int x,y;
 cout<<"Who was the first man to land on the moon"<<endl;
 cout<<"(1)Neal amstrom            (2)Lunar moon"<<endl;
 cout<<"(3)Adem ray               (4)Donlad edison"<<endl;
 cin>>x;
 switch (x)
 {case 1:
 cout<<"Congo you are going to the next round";
 break;
 case 2:
 cout<<"Sorry you cannot continue";
 break;
 case 3:
 cout<<"Sorry you cannot continue";
 break;
 case 4:
 cout<<"Sorry you cannot continue";
 break;
}
 getch();
}